### ISSUE TITLE
NullReferenceException on RedirectCalls

### ISSUE THREAD

**Issue by seiggy** [seiggy/Skylines-Traffic-Manager#4]
Attempting to make a new map with all other mods and assets disabled results in this error:
NullReferenceException at TrafficManager.RedirectionHelper.RedirectCalls

**Comment by boformer** [comment]
A little bit more information like the stack trace would be great.

Click the "Copy" button in C:SL's exception window to obtain the full stack trace.

**Comment by seiggy** [comment]
Yeah, pulled the issue from my Steam Workshop page comment thread. Going to try and replicate the issue asap and I'll grab stack traces etc then.

**Comment by seiggy** [comment]
Found problem. Issue fixed in commit https://github.com/seiggy/Skylines-Traffic-Manager/commit/866b4848660fdf788ade15db147d59e088fd9d3b
