### ISSUE TITLE
No timed traffic lights after loading a save game

### ISSUE THREAD

**Issue by anzhe778** [seiggy/Skylines-Traffic-Manager#5]
Hello,

after loading the save game, the timed traffic lights stop functioning. After I click on Timed Traffic Lights and select a node with previously set up timed traffic lights, it appears as the previous setup is not there. Yet I am also unable to add timed traffic lights again, because the 'next' button is unresponsive.

After I choose 'manual traffic lights' it appears that the previous timed traffic light setup is working, but I am not able to edit it.

I use both Traffic++ and TrafficManager Plus.

save file is here: https://drive.google.com/file/d/0B6J5dSMoc9JAUzRiN2V4Tjh1NUE/view?usp=sharing

Best regards,
Andrzej

**Comment by seiggy** [comment]
Thanks. Probably also related to the negative timed traffic light bug. As I rewrite the save system this weekend, hopefully it will squash this bug.

**Comment by anzhe778** [comment]
Just to confirm hat the issue has been fixed with new save game system. Thank you for your work!

**Comment by seiggy** [comment]
Yay! Thanks for the confirmation!
