### ISSUE TITLE
Negative Counter for timed Traffic Lights

### ISSUE THREAD

**Issue by philipp94831** [seiggy/Skylines-Traffic-Manager#6]
I get negative counters for all of my timed traffic lights. Never saved to cloud at anytime...

**Comment by seiggy** [comment]
Replication steps from user on Steam:

> The bug happens when you modify a street segmet that is connected to an intersection that runs a timed script. Deleting a connected road or upgrading/downgrading a segment breaks the node. This means the script that belongs to the node is not editable any more or the intersection even gets a new node, making the old node and hence the timed script inaccessible. This means, ones the script is broken due to changes to the intersection, the timed script for that node cannot be deleted anymore, so this basically ruins timed traffic lights for this entire savegame. The only way around so far is, before making any changes to a road/intersection, make sure it has not timed traffic scripts running for it, or delete the script before making changes.

This bug will be squashed this weekend. I'm rewriting the save system, and looking into how Traffic++ writes out their data. Hopefully after the next patch, this bug will be squashed, AND cloud saves should be supported as well.

**Comment by seiggy** [comment]
Latest patch should have this fixed.
